dependencies:
    - base
    - cmdargs
    - fsnotify < 0.4
    - lens
    - containers
    - time
    - directory
    - filepath
    - bytestring
    - process
    - language-c-quote
    - mainland-pretty
    - srcloc
    - pretty-show
    - transformers
    - PyF


data-files:
  - main.c
  - template.c
  - main_hot.c
  - Makefile
  - vendor/Makefile

default-extensions:
  - BlockArguments
  - DeriveDataTypeable
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - TupleSections
  - ViewPatterns
  - ScopedTypeVariables

executable:
  main: main.hs
  source-dirs: hs

tests:
  hspec:
    main: Spec.hs
    source-dirs:
      - hs
      - hstest
    build-tools: hspec-discover
    dependencies:
      - hspec-golden
      - hspec
      - hspec-core
