dependencies:
    - base
    - cmdargs
    - fsnotify < 0.4
    - lens
    - containers
    - time
    - directory
    - filepath
    - bytestring
    - process
    - language-c-quote
    - mainland-pretty
    - srcloc
    - pretty-show
    - transformers

data-files:
  - main.c
  - template.c
  - main_hot.c
  - Makefile
  - vendor/Makefile

default-extensions:
  - BlockArguments
  - DeriveDataTypeable
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - PatternSynonyms
  - QuasiQuotes
  - RecordWildCards
  - TupleSections
  - ViewPatterns

executable:
  main: main.hs
  source-dirs: .
