dependencies:
    - base
    - language-c
    - cmdargs
    - fsnotify
    - lens
    - containers
    - time
    - directory
    - filepath
    - bytestring

data-files:
  - main.c
  - template.c
  - main_hot.c
  - Makefile
  - vendor/Makefile

default-extensions:
  - BlockArguments
  - DeriveDataTypeable
  - FlexibleInstances
  - LambdaCase
  - NamedFieldPuns
  - RecordWildCards
  - TupleSections
  - ViewPatterns

executable:
  main:
    main.hs
  hs-source-dirs:
    - .
